server:
  port: 8080
spring:
  application:
    name: "MsFundRequest"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
  sql:
    init:
      mode: always
  r2dbc:
    schema:
      create-mode: always
      locations: classpath:schema.sql
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"

routes:
  paths:
    funds: "/api/v1/funds"
    fundsById: "/api/v1/funds/{id}"

adapters:
  r2dbc:
    host: "localhost"
    port: 5432
    database: "postgres"
    schema: "public"
    username: "postgres"
    password: "postgres"
