package co.com.crediya.enums;

public enum FundErrorEnum {

    DOCUMENT_IDENTIFICATION_NOT_FOUND,
    LOAN_TYPE_ID_NOT_FOUND,
    LOAN_AMOUNT_OUT_OF_RANGE,
    TOKEN_USER_MISMATCH,
    EMAIL_NOT_FOUND,
    DOCUMENT_IDENTIFICATION_NOT_FOUND_IN_AUTH,
    FUND_APPLICATION_ID_NOT_FOUND,
    OBJECT_STATUS_ID_NOT_VALID,
    USER_NOT_FOUND,
    FUND_APPLICATION_STATUS_IS_THE_SAME
}
