package co.com.crediya.enums;

public enum FundErrorEnum {

    DOCUMENT_IDENTIFICATION_NOT_FOUND,
    LOAN_TYPE_ID_NOT_FOUND,
    LOAN_AMOUNT_OUT_OF_RANGE,
    INVALID_TOKEN,
    TOKEN_USER_MISMATCH,
    STATUS_FUND_NAME_NOT_FOUND,
    FUND_STATUS_INVALID,
    LOAN_TYPE_INVALID
}
